type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  profilePictureUrl: String
  bio: String
}

type Image @table {
  imageUrl: String!
  prompt: String!
  aiModel: String!
  createdAt: Timestamp!
  description: String
  aspectRatio: String
  user: User
}

type Like @table(key: ["user", "image"]) {
  createdAt: Timestamp!
  user: User!
  image: Image!
}

type Comment @table {
  text: String!
  createdAt: Timestamp!
  user: User
  image: Image
}

type Follow @table(key: ["follower", "followee"]) {
  createdAt: Timestamp!
  follower: User!
  followee: User!
}